name: .NET

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore StockGame.sln
    - name: Build
      run: dotnet build StockGame.sln --no-restore
    - name: Test
      run: dotnet test StockGame.sln --no-build --verbosity normal